# Generated by Django 5.2 on 2025-12-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="video",
            field=models.FileField(
                blank=True, help_text="Movie video file", null=True, upload_to="videos/"
            ),
        ),
    ]
